influxdata/pbjson

pbjson-build/src/lib.rs
Allow overriding the output directory, as does tonic_build, lets us target different locations for building
Add an API mirroring `tonic_build ` to explicitly override the output directory
See reference https://docs.rs/tonic-build/0.5.2/tonic_build/struct.Builder.html#method.out_dir
copy/paste implementation from tonic-build:https://docs.rs/tonic-build/0.5.2/src/tonic_build/prost.rs.html#261-267
=> feat: add Builder::out_dir to set output directory

.cargo/audit.toml
Chrono is solely used for datetime formatting, so should be fine
=> chore: suppress RUSTSEC-2020-0071 and RUSTSEC-2020-0159

pbjson-build/src/descriptor.rs, pbjson-build/src/generator.rs, pbjson-build/src/generator/enumeration.rs, pbjson-build/src/generator/message.rs, pbjson-build/src/lib.rs, pbjson-build/src/message.rs, pbjson-build/src/resolver.rs, pbjson-test/build.rs, pbjson-test/protos/common.proto, pbjson-test/protos/external.proto, pbjson-test/protos/syntax3.proto, pbjson-test/src/lib.rs
This adds support for extern_types, whilst also fixing a bug in the type resolution that would cause invalid code generation for field serializers of enumerations defined in different packages.
Closes #9
=> feat: fix resolver (#9)

pbjson-build/src/descriptor.rs, pbjson-build/src/lib.rs, pbjson-build/src/resolver.rs, pbjson-test/protos/syntax3.proto, pbjson-test/src/lib.rs
The current logic to handle enumerations will never generate incorrect serialization code, but will panic if the protobuf definition contains lower case characters. This PR fixes that, and also adds in the ability to disable enum prefix stripping, a feature which prost also has.
The [protobuf spec](https://developers.google.com/protocol-buffers/docs/proto3#json) says that enum variants be encoded as-is in the proto definitions, and so that is what this PR does. If your proto definition has mixed capitalisation, so will your JSON payloads.
This must also follow the same logic used by prost to [strip enum prefixes](https://github.com/tokio-rs/prost/blob/d45a37cab69c2a0cda36a97df8823fcaf43dc1fe/prost-build/src/code_generator.rs#L998) to ensure we generate correct code.
Closes #15
=> fix: encoding of mixed case enumerations (#15)

pbjson-types/build.rs, pbjson-types/src/lib.rs, pbjson-types/src/list_value.rs, pbjson-types/src/null_value.rs, pbjson-types/src/struct.rs, pbjson-types/src/value.rs
This PR adds `serde` support for `google.protobuf.Value`.
closes #5 
Depends on #14
=> Add serde support for Value

pbjson-types/Cargo.toml
This was disabled in #19 but I forgot to check the crates still built independently. The alloc feature is needed for string formatting support
=> chore: fix chrono feature flag

pbjson/Cargo.toml, pbjson/src/lib.rs
There might be smarter ways to detect this, but this was the quickest solution I could come up with.
Closes #22
=> feat: support URL-safe base64 strings (#22)

pbjson-build/src/generator/message.rs, pbjson-test/protos/syntax3.proto, pbjson-test/src/lib.rs
Closes #23 
Whilst implementing this I realised #27 is an issue, but going to punt on fixing that for now. It's not a quick fix, and very niche.
=> feat: add support for bytes values in maps (#23)

pbjson-build/src/generator.rs, pbjson-build/src/generator/enumeration.rs, pbjson-build/src/generator/message.rs
I had a case where `message Result` was defined in the proto files, and generated code was trying to use that instead of Rust's `Result` type.
The solution was to have the full path of `Result` type in the generated code.
=> pbjson-build: Use `std::result::Result` in the generated code

pbjson-build/Cargo.toml, pbjson-test/Cargo.toml, pbjson-types/Cargo.toml, pbjson/Cargo.toml
Prepare the 0.2.3 release.
This contains:
* https://github.com/influxdata/pbjson/pull/26
* https://github.com/influxdata/pbjson/pull/28
* https://github.com/influxdata/pbjson/pull/21
* https://github.com/influxdata/pbjson/pull/33
None of which should be breaking
=> chore: prepare 0.2.3 release

pbjson-build/src/descriptor.rs, pbjson-build/src/lib.rs
I am working on preparing a release of [`protoc-gen-prost`](https://github.com/neoeinstein/protoc-gen-prost), which will be able to be used as a `protoc` plugin and fit really nicely into the [`buf`](https://buf.build) ecosystem. The PR which enables this for `prost` was merged in as tokio-rs/prost#598. As part of that, I wanted to include the ability to easily generate `serde` impls using another companion crate: `protoc-gen-prost-serde`. This requires two small changes: expose `Builder::generate()` and add a new function to allow registering already decoded `FileDescriptorProto`s.
My utility is pending release on Crates.io, waiting for the next release of prost, and I'd love to include this functionality too. The code in my repository has already been updated using a patched reference …
=> feat: allow code generation that does not access the file system

pbjson-test/Cargo.toml, pbjson-test/build.rs
As pointed out by @neoeinstein in https://github.com/influxdata/pbjson/pull/35#issuecomment-1083521984 I accidentally missed this in #39
=> chore: update prost in tests

.circleci/config.yml
The docs upload is taking longer than the rest of the CI pipeline. This changes to uploading a compressed tarball which will be significantly faster. For reference the same change was made to IOx last year - https://github.com/influxdata/influxdb_iox/pull/2880
=> chore: compress CI docs

pbjson-build/Cargo.toml, pbjson-test/Cargo.toml, pbjson-types/Cargo.toml, pbjson/Cargo.toml
Includes
* https://github.com/influxdata/pbjson/pull/39
* https://github.com/influxdata/pbjson/pull/35
Technically this is not a breaking change in so much as pbjson doesn't have any breaking changes, but it is a breaking prost upgrade so best to follow along given the degree of coupling between the projects.
=> chore: prepare 0.3 release

.circleci/config.yml, pbjson-build/src/generator/message.rs, pbjson-build/src/lib.rs, pbjson-test/Cargo.toml, pbjson-test/build.rs, pbjson-test/src/lib.rs
Allow skipping unknown fields when deserializing.
I added a flag to to the builder, so this behavior is opt-in, keeping
the old behavior (error out for unknown fields) as default.
This is mostly required for forward compatibility, when new fields
are added, any old instance will fail to deserialize a message
serialized with a newer version. This is also aligned with prost that
skips any unknown field too.
Added a special variant `GeneratedField::__SkipField__` that is used every time an unknown field is encountered, which then is used to consume and ignore the value of the field. This will be added only if the `skip_unknown_fields` flag is set.
To set the flag, a new `Builder::skip_unknown_fields` function was added.
I generated the code for the tests twice, to test the skip functionality …
=> feat: add flag to skip unknown fields instead of error

pbjson-build/src/generator/message.rs, pbjson-test/build.rs, pbjson-test/protos/duplicate_name.proto, pbjson-test/src/lib.rs
#45 
Adding Suffix `__` for the variable which named by `proto field`.
Notice: can't add Prefix, beacuse of `__r#type` is invalid.
=> fix: escape field names in generated code (#45) 

pbjson-build/src/resolver.rs
[Issue 48](https://github.com/influxdata/pbjson/issues/48)
hey 👋 
shared prefix should only count matches until a type name does not match
=> fix: shared prefix match

pbjson-build/Cargo.toml, pbjson-test/Cargo.toml, pbjson-types/Cargo.toml
This updates the dependencies on `prost`, `prost-types` and `prost-build` to the latest released version of prost.
As a user of `pbjson` and `pbjson-types` this change to the pbjson crates is necessary when trying to use the recently released `tonic` v0.8.0 along with the pbjson crates, as tonic has been updated to depend on this newer version of the prost crates.
Can this change be included in your release of pbjson v0.4.0? #54
=> chore: Update prost, prost-types and prost-build dependencies

pbjson-build/Cargo.toml, pbjson-test/Cargo.toml, pbjson-types/Cargo.toml, pbjson/Cargo.toml
Includes #53 #52 
This is a breaking change release as https://github.com/influxdata/pbjson/pull/52 alters the paths of generated `.rs` files if they contain camelcase paths.
=> chore: prepare 0.4

pbjson-test/src/lib.rs, pbjson-types/build.rs, pbjson-types/src/lib.rs, pbjson-types/src/wrappers.rs
=> feat: Correct Serialization of google::protobuf::*Value Types

pbjson-build/src/generator/message.rs
Noticed whilst reviewing #63, we have supported serializing bytes to base64 for a while now
=> chore: update module doc

.circleci/config.yml, pbjson-build/Cargo.toml, pbjson-build/src/generator/message.rs, pbjson-build/src/lib.rs, pbjson-test/Cargo.toml, pbjson-test/build.rs, pbjson-test/src/lib.rs
https://developers.google.com/protocol-buffers/docs/proto3#json_options
=> feat: add feature `emit_fields`

pbjson-build/src/descriptor.rs, pbjson-build/src/resolver.rs, pbjson-test/build.rs, pbjson-test/protos/escape.proto, pbjson-test/src/lib.rs
=> fix: escape keywords in TypeName

pbjson-build/Cargo.toml, pbjson-test/Cargo.toml, pbjson-types/Cargo.toml, pbjson/Cargo.toml
We've built up a fair few changes, so I think it is time for another release. This is a major release as it changes the serialization of `*Value` types to be more correct.
* https://github.com/influxdata/pbjson/pull/63 by @rise0chen 
* https://github.com/influxdata/pbjson/pull/64 by @tustvold 
* https://github.com/influxdata/pbjson/pull/65 by @rise0chen 
* https://github.com/influxdata/pbjson/pull/66 by @rise0chen 
* https://github.com/influxdata/pbjson/pull/67 by @mbrobbel 
* https://github.com/influxdata/pbjson/pull/69 by @rise0chen
=> chore: prepare 0.5 release

pbjson-test/src/lib.rs, pbjson-types/src/duration.rs, pbjson-types/src/timestamp.rs, pbjson/src/lib.rs
The pattern "let s: &str = Deserialize::deserialize(deser)" used in multiple places is not ideal, as it generates errors when the deserializer uses an IO Reader and not a string. To fix this, implementing a visitor is preferred, as it gives the deserializer the choice of allocating or not a string.
To ensure the issue is fixed, the tests now deserialize both from a string and from a reader.
I haven't used the same fix for the integer/string deserialization for numbers. Using a Visitor is much more cumbersome as it would depend on each numeric type, and using a Cow type is enough to fix the issue.
Closes #55
=> fix: properly handle deserialization from Reader

pbjson-build/src/generator/message.rs, pbjson-test/src/lib.rs
For message fields, the proto3 json specification requires parsers to accept both lowerCamelCase names and the original proto field names.
This change adapts the deserialization code-gen to accept the proto name.
=> feat: accept proto field name when deserializing

.circleci/config.yml, pbjson-build/src/generator/message.rs, pbjson-build/src/lib.rs, pbjson-test/Cargo.toml, pbjson-test/build.rs, pbjson-test/src/lib.rs
This change adds a flag to the code-gen builder, allowing output json
fields to use their proto-schema defined field names instead of being
converted to lowerCamelCase.
Preserving proto field names is mentioned as an optional feature in the
protobuf json specification[1]. This change builds on the previous
support[2] for deserializing preserved proto field names.
[1]: https://developers.google.com/protocol-buffers/docs/proto3#json_options
[2]: https://github.com/influxdata/pbjson/pull/72
=> feat: Optionally preserve proto field names

pbjson-build/src/generator/message.rs, pbjson-test/protos/syntax3.proto, pbjson-test/src/lib.rs
Adds support for explicit null values where the corresponding protobuf values are nullable.
It is worth highlighting that JSON supports greater nullability than protobuf, and this leads to a couple of places where `null` is still invalid.
**List Elements are not Nullable**
```
message Test {
repeated int32 mylist = 1;
}
```
```
{
"mylist": [null] <-- invalid
}
```
**Oneof nulls are not typed**
```
message Test {
oneof foo {
int32 a = 1;
int32 b = 2;
}
}
```
```
{
"a": null
}
```
Will get converted to `{foo: None}` which loses the fact the null was encoded on `a`
=> feat: support deserializing explicit nulls (#73)

pbjson-build/src/descriptor.rs, pbjson-build/src/escape.rs, pbjson-build/src/generator/enumeration.rs, pbjson-build/src/generator/message.rs, pbjson-build/src/message.rs, pbjson-test/build.rs, pbjson-test/protos/duplicate_number.proto, pbjson-test/src/lib.rs
I've redone the fixes from the old #30 PR and added the missing test. I've also signed the CLA.
=> fix: Resolve Envoy xDS proto issues

pbjson-build/src/generator/message.rs
This avoids compilation errors where the source proto files declare a `Result` type.
=> chore: fix two cases where std::result::Result is not fully scoped

pbjson-build/Cargo.toml
~Draft as it builds on https://github.com/influxdata/pbjson/pull/128~
As part of preparing a new release, https://github.com/influxdata/pbjson/issues/127 let's update the other dependencies 🎉 
1. Update itertools and heck dependencies
=> chore: update dependencies: heck to `0.5` and itertools to `0.13.0` 

pbjson-build/Cargo.toml, pbjson-test/Cargo.toml, pbjson-types/Cargo.toml, pbjson/Cargo.toml
Rationale: prepare for https://github.com/influxdata/pbjson/issues/127
Modeled after https://github.com/influxdata/pbjson/pull/112 from @tustvold 
I don't really have a great idea if updating to a new prost dependency https://github.com/influxdata/pbjson/pull/126 constitutes a breaking API change but let's play it safe and assume so and pump the pre-release major version
=> chore: Prepare `0.7.0` release

RELEASING.md
As part of https://github.com/influxdata/pbjson/issues/127 I had to figure some of this out, and it would be nice to have it written down for next time
=> docs: Document Release Process
